remote_theme: eliottvincent/bay

header:
  pages:
    - name: O mnie |
      slug: /
    - name: Case Study |
    - name: CV

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: anitakasperekux@gmail.com
      link: anitakasperekux@gmail.com
    - name: WeChat
      value: + 48 728031964 
      link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/anita_kasperek
      username: "@anita_kasperek"
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/anita-kasperek/
    - name: Dribbble
      link: https://dribbble.com/anita_kasperek

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
